AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvParameter:
    Default: dev
    Type: String
    AllowedValues: 
      - dev
      - int
      - prod
  GitShaParameter:
    Type: String

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:
  scarcityApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Sub "scarcity-objects-${EnvParameter}"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

# Outputs:
#   set of outputs